name: RueBémol
favicon: null
layout_spectrum: 0.24325
typography_spectrum: 0.58206
title: RueBémol - agence des arts de la rue
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#ffffff'
    - '#8e6049'
    - '#0e39bb'
    - '#bc9f8d'
  brandStrength: 0.6875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
