name: RueBémol
favicon: null
layout_spectrum: 0.24325
typography_spectrum: 0.64152
title: RueBémol - agence des arts de la rue
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#91fffe'
    - '#0c0b10'
    - '#83aed9'
    - '#5c5754'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
